#!/bin/sh

volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

case "$volume" in
    *"[MUTED]"*)
        text="Muted"
        ;;
    *)
        text="Volume:"
        ;;
esac

volume=$(echo "$volume" | awk '{print $2}')
volume=$(echo "( $volume * 100 ) / 1" | bc)

notify-send -t 1000 -a 'wp-vol' -h string:x-canonical-private-synchronous:volume -h int:value:$volume "$text ${volume}%"
